import {
  AlertCircle,
  AlertTriangle,
  Archive,
  Award,
  BarChart3,
  Banknote,
  Bell,
  BookOpen,
  Boxes,
  Brain,
  Building,
  Calendar,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  Cog,
  Code,
  CreditCard,
  FileBarChart,
  FileBarChart2,
  FileText,
  FolderKanban,
  Forklift,
  FormInput,
  Gauge,
  GraduationCap,
  Hammer,
  HardHat,
  Heart,
  HelpCircle,
  Kanban,
  LayoutDashboard,
  Mail,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Package,
  Phone,
  Receipt,
  Send,
  Settings,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Store,
  TrendingDown,
  Truck,
  Users,
  User,
  UserCog,
  Wrench,
} from 'lucide-react';
import { LucideIcon } from 'lucide-react';

export type NavigationSurface = 'sidebar' | 'mobileHeader' | 'mobileMenu' | 'navbar';

export interface NavigationItem {
  title: string;
  href: string;
  icon: LucideIcon;
  description?: string;
  permissionModule?: string;
  surfaces?: NavigationSurface[];
}

export interface NavigationSection {
  title: string;
  icon?: LucideIcon;
  items: NavigationItem[];
}

const sidebarAndMobileMenu: NavigationSurface[] = ['sidebar', 'mobileMenu'];
const allSurfaces: NavigationSurface[] = ['sidebar', 'mobileHeader', 'mobileMenu'];
const navbarSurfaces: NavigationSurface[] = ['navbar', 'sidebar', 'mobileHeader', 'mobileMenu'];
const mobileMenuOnly: NavigationSurface[] = ['mobileMenu'];

export const appNavigation: NavigationSection[] = [
  {
    title: 'Dashboard',
    items: [
      {
        title: 'Dashboard',
        href: '/dashboard',
        icon: LayoutDashboard,
        description: 'Main dashboard overview',
        surfaces: navbarSurfaces,
      },
    ],
  },
  {
    title: 'Customers',
    items: [
      {
        title: 'Customers',
        href: '/customers',
        icon: Users,
        description: 'Manage customer database',
        permissionModule: 'customers',
        surfaces: navbarSurfaces,
      },
    ],
  },
  {
    title: 'Inventory',
    icon: Package,
    items: [
      {
        title: 'Inventory Overview',
        href: '/inventory',
        icon: Package,
        description: 'Main inventory overview',
        permissionModule: 'inventory',
        surfaces: navbarSurfaces,
      },
      {
        title: 'Service Packages',
        href: '/service-packages',
        icon: Boxes,
        description: 'Service templates with parts',
        permissionModule: 'service_packages',
        surfaces: allSurfaces,
      },
      {
        title: 'Asset Usage',
        href: '/asset-usage',
        icon: Gauge,
        description: 'Track vehicle and equipment usage',
        permissionModule: 'equipment_tracking',
        surfaces: allSurfaces,
      },
      {
        title: 'Consumption Tracking',
        href: '/consumption-tracking',
        icon: TrendingDown,
        description: 'Log parts consumption',
        permissionModule: 'inventory',
        surfaces: allSurfaces,
      },
      {
        title: 'Mobile Scanner',
        href: '/mobile-inventory',
        icon: Smartphone,
        description: 'Quick stock adjustments',
        permissionModule: 'inventory',
        surfaces: allSurfaces,
      },
      {
        title: 'Inventory Analytics',
        href: '/inventory-analytics',
        icon: BarChart3,
        description: 'Forecasting and analytics',
        permissionModule: 'analytics',
        surfaces: allSurfaces,
      },
      {
        title: 'Inventory Manager',
        href: '/inventory-manager',
        icon: Settings,
        description: 'Advanced inventory settings',
        permissionModule: 'inventory',
        surfaces: allSurfaces,
      },
      {
        title: 'Maintenance Planning',
        href: '/maintenance-planning',
        icon: Wrench,
        description: 'Predictive maintenance and scheduling',
        permissionModule: 'maintenance_requests',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Procurement',
    items: [
      {
        title: 'RFQs',
        href: '/procurement/rfqs',
        icon: FileText,
        description: 'Request quotes from vendors',
        permissionModule: 'inventory',
        surfaces: allSurfaces,
      },
      {
        title: 'Receiving',
        href: '/procurement/receiving',
        icon: ClipboardCheck,
        description: 'Log receipts and discrepancies',
        permissionModule: 'inventory',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Scheduling',
    items: [
      {
        title: 'Planner',
        href: '/planner',
        icon: Kanban,
        description: 'Visual planning board for work and resources',
        permissionModule: 'work_orders',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Service Calendar',
        href: '/calendar',
        icon: Calendar,
        description: 'Work orders, maintenance and repairs scheduling',
        permissionModule: 'calendar',
        surfaces: allSurfaces,
      },
      {
        title: 'Staff Scheduling',
        href: '/scheduling',
        icon: UserCog,
        description: 'Employee schedules and asset assignments',
        permissionModule: 'team',
        surfaces: allSurfaces,
      },
      {
        title: 'Service Reminders',
        href: '/service-reminders',
        icon: Bell,
        description: 'Manage service reminders',
        permissionModule: 'service_reminders',
        surfaces: allSurfaces,
      },
      {
        title: 'Projects',
        href: '/projects',
        icon: FolderKanban,
        description: 'Multi-year project planning and budgets',
        permissionModule: 'work_orders',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Timesheet',
        href: '/timesheet',
        icon: ClipboardList,
        description: 'Track work hours and attendance',
        surfaces: sidebarAndMobileMenu,
      },
    ],
  },
  {
    title: 'Communications',
    items: [
      {
        title: 'Team Chat',
        href: '/chat',
        icon: MessageCircle,
        description: 'Internal team messaging',
        permissionModule: 'team_chat',
        surfaces: allSurfaces,
      },
      {
        title: 'Customer Communications',
        href: '/customer-communications',
        icon: MessageSquare,
        description: 'SMS templates and communications',
        permissionModule: 'customer_communications',
        surfaces: allSurfaces,
      },
      {
        title: 'Call Logger',
        href: '/call-logger',
        icon: Phone,
        description: 'Log customer calls',
        permissionModule: 'call_logger',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Marketing',
    items: [
      {
        title: 'Email Campaigns',
        href: '/email-campaigns',
        icon: Mail,
        description: 'Manage email campaigns',
        permissionModule: 'email_campaigns',
        surfaces: allSurfaces,
      },
      {
        title: 'Email Sequences',
        href: '/email-sequences',
        icon: Send,
        description: 'Automated email workflows',
        permissionModule: 'marketing',
        surfaces: allSurfaces,
      },
      {
        title: 'Email Templates',
        href: '/email-templates',
        icon: FileText,
        description: 'Email template library',
        permissionModule: 'marketing',
        surfaces: allSurfaces,
      },
      {
        title: 'SMS Management',
        href: '/sms-management',
        icon: MessagesSquare,
        description: 'SMS campaigns and bulk messaging',
        permissionModule: 'sms_management',
        surfaces: allSurfaces,
      },
      {
        title: 'SMS Templates',
        href: '/sms-templates',
        icon: MessageSquare,
        description: 'SMS template library',
        permissionModule: 'marketing',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Operations',
    items: [
      {
        title: 'Quotes',
        href: '/quotes',
        icon: FileText,
        description: 'Manage quotes and estimates',
        permissionModule: 'quotes',
        surfaces: allSurfaces,
      },
      {
        title: 'Work Orders',
        href: '/work-orders',
        icon: Wrench,
        description: 'Manage work orders',
        permissionModule: 'work_orders',
        surfaces: navbarSurfaces,
      },
      {
        title: 'Daily Logs',
        href: '/daily-logs',
        icon: FileText,
        description: 'Daily operational logs',
        permissionModule: 'work_orders',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Invoices',
        href: '/invoices',
        icon: Receipt,
        description: 'Manage invoices',
        permissionModule: 'invoices',
        surfaces: allSurfaces,
      },
      {
        title: 'Service Board',
        href: '/service-board',
        icon: ClipboardList,
        description: 'Service management board',
        permissionModule: 'work_orders',
        surfaces: allSurfaces,
      },
      {
        title: 'Payments',
        href: '/payments',
        icon: ShoppingBag,
        description: 'Payment processing',
        permissionModule: 'payments',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Finance',
    items: [
      {
        title: 'Finance Dashboard',
        href: '/finance',
        icon: BarChart3,
        description: 'Finance overview and KPIs',
        permissionModule: 'accounting',
        surfaces: allSurfaces,
      },
      {
        title: 'Accounts Payable',
        href: '/finance/accounts-payable',
        icon: Receipt,
        description: 'Vendor bills and approvals',
        permissionModule: 'accounting',
        surfaces: allSurfaces,
      },
      {
        title: 'Accounts Receivable',
        href: '/finance/accounts-receivable',
        icon: CreditCard,
        description: 'Customer invoices and balances',
        permissionModule: 'accounting',
        surfaces: allSurfaces,
      },
      {
        title: 'General Ledger',
        href: '/finance/general-ledger',
        icon: BookOpen,
        description: 'Chart of accounts and ledger',
        permissionModule: 'accounting',
        surfaces: allSurfaces,
      },
      {
        title: 'Journal Entries',
        href: '/finance/journal-entries',
        icon: FileText,
        description: 'Posted and draft journals',
        permissionModule: 'accounting',
        surfaces: allSurfaces,
      },
      {
        title: 'Bank Reconciliation',
        href: '/finance/bank-reconciliation',
        icon: Banknote,
        description: 'Bank balances and reconciliation',
        permissionModule: 'accounting',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Equipment and Tools',
    items: [
      {
        title: 'Equipment Management',
        href: '/equipment-management',
        icon: Hammer,
        description: 'Manage equipment, tools, and maintenance',
        permissionModule: 'equipment_tracking',
        surfaces: allSurfaces,
      },
      {
        title: 'Fleet Management',
        href: '/fleet-management',
        icon: Truck,
        description: 'Manage company vehicles and fleet',
        permissionModule: 'fleet_management',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Equipment',
        href: '/equipment',
        icon: Package,
        description: 'Shop equipment and assets',
        permissionModule: 'equipment_tracking',
        surfaces: mobileMenuOnly,
      },
      {
        title: 'Safety Equipment',
        href: '/safety-equipment',
        icon: Shield,
        description: 'Safety equipment and compliance',
        permissionModule: 'safety',
        surfaces: mobileMenuOnly,
      },
      {
        title: 'Equipment Tracking',
        href: '/equipment-tracking',
        icon: Package,
        description: 'Track equipment location and status',
        permissionModule: 'equipment_tracking',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Maintenance Requests',
        href: '/maintenance-requests',
        icon: AlertCircle,
        description: 'Track maintenance requests',
        permissionModule: 'maintenance_requests',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Fleet Operations',
    icon: Truck,
    items: [
      {
        title: 'Fuel Management',
        href: '/fuel-management',
        icon: Gauge,
        description: 'Track fuel entries, cards, and costs',
        permissionModule: 'fleet_management',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Warranty Tracking',
        href: '/warranties',
        icon: Shield,
        description: 'Manage warranties and claims',
        permissionModule: 'fleet_management',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Driver Management',
        href: '/driver-management',
        icon: UserCog,
        description: 'Driver profiles, licenses, and compliance',
        permissionModule: 'fleet_management',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Tire Management',
        href: '/tire-management',
        icon: Package,
        description: 'Tire inventory and lifecycle tracking',
        permissionModule: 'fleet_management',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Accounting Integration',
        href: '/accounting-integration',
        icon: Receipt,
        description: 'QuickBooks, Sage, and journal entries',
        permissionModule: 'fleet_management',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Insurance',
        href: '/insurance',
        icon: Shield,
        description: 'Fleet and equipment insurance',
        permissionModule: 'fleet_management',
        surfaces: sidebarAndMobileMenu,
      },
    ],
  },
  {
    title: 'Safety and Compliance',
    icon: HardHat,
    items: [
      {
        title: 'Safety Dashboard',
        href: '/safety',
        icon: Shield,
        description: 'Safety overview and metrics',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Incidents',
        href: '/safety/incidents',
        icon: AlertTriangle,
        description: 'Report and track incidents',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Daily Inspections',
        href: '/safety/inspections',
        icon: ClipboardCheck,
        description: 'Shop safety inspections',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'DVIR Reports',
        href: '/safety/dvir',
        icon: Truck,
        description: 'Vehicle inspection reports',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Vessel Inspections',
        href: '/safety/vessels',
        icon: Ship,
        description: 'Marine vessel pre-trip inspections',
        permissionModule: 'safety',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Forklift Inspections',
        href: '/safety/equipment/forklift',
        icon: Forklift,
        description: 'Forklift safety inspections',
        permissionModule: 'safety',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Lift Inspections',
        href: '/safety/equipment',
        icon: Wrench,
        description: 'Equipment safety checks',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Certifications',
        href: '/safety/certifications',
        icon: Award,
        description: 'Staff certifications and training',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Safety Documents',
        href: '/safety/documents',
        icon: FileText,
        description: 'SDS, procedures, manuals',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Schedules and Reminders',
        href: '/safety/schedules',
        icon: CalendarClock,
        description: 'Safety compliance schedules',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Safety Analytics',
        href: '/safety/analytics',
        icon: BarChart3,
        description: 'Inspection trends and alerts',
        permissionModule: 'safety',
        surfaces: mobileMenuOnly,
      },
      {
        title: 'Reports',
        href: '/safety/reports',
        icon: FileText,
        description: 'Safety reports and compliance',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Corrective Actions',
        href: '/safety/corrective-actions',
        icon: ClipboardCheck,
        description: 'CAPA tracking',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Near Miss',
        href: '/safety/near-miss',
        icon: AlertTriangle,
        description: 'Report close calls',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Training',
        href: '/safety/training',
        icon: GraduationCap,
        description: 'Training courses and assignments',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Meetings',
        href: '/safety/meetings',
        icon: Users,
        description: 'Toolbox talks and meetings',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Job Safety Analysis',
        href: '/safety/jsa',
        icon: ClipboardCheck,
        description: 'JSA hazard assessments',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'PPE Management',
        href: '/safety/ppe',
        icon: HardHat,
        description: 'PPE inventory and assignments',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Contractor Safety',
        href: '/safety/contractors',
        icon: HardHat,
        description: 'Contractor compliance and access',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
      {
        title: 'Safety Rewards',
        href: '/safety/rewards',
        icon: Award,
        description: 'Points and gamification',
        permissionModule: 'safety',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Quality',
    items: [
      {
        title: 'Quality Dashboard',
        href: '/quality',
        icon: ClipboardCheck,
        description: 'Quality metrics and checkpoints',
        permissionModule: 'reports',
        surfaces: allSurfaces,
      },
      {
        title: 'Nonconformances',
        href: '/quality/nonconformances',
        icon: AlertTriangle,
        description: 'Track quality issues',
        permissionModule: 'reports',
        surfaces: allSurfaces,
      },
      {
        title: 'Quality Checklists',
        href: '/quality/checklists',
        icon: ClipboardList,
        description: 'QC checklist library',
        permissionModule: 'reports',
        surfaces: allSurfaces,
      },
      {
        title: 'CAPA',
        href: '/quality/capa',
        icon: ClipboardCheck,
        description: 'Corrective and preventive actions',
        permissionModule: 'reports',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Company',
    items: [
      {
        title: 'Company Profile',
        href: '/company-profile',
        icon: Building,
        description: 'Company information',
        permissionModule: 'settings',
        surfaces: allSurfaces,
      },
      {
        title: 'Team',
        href: '/team',
        icon: UserCog,
        description: 'Team management',
        permissionModule: 'team',
        surfaces: allSurfaces,
      },
      {
        title: 'Payroll',
        href: '/payroll',
        icon: ClipboardList,
        description: 'Time tracking and payroll',
        permissionModule: 'team',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Training Overview',
        href: '/training-overview',
        icon: GraduationCap,
        description: 'Monitor team certifications and training',
        permissionModule: 'team',
        surfaces: allSurfaces,
      },
      {
        title: 'Vehicles',
        href: '/vehicles',
        icon: Truck,
        description: 'Fleet management',
        permissionModule: 'fleet_management',
        surfaces: allSurfaces,
      },
      {
        title: 'Documents',
        href: '/documents',
        icon: FileBarChart,
        description: 'Document management',
        permissionModule: 'documents',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Services',
    items: [
      {
        title: 'Service Editor',
        href: '/service-editor',
        icon: Cog,
        description: 'Edit service offerings',
        permissionModule: 'service_catalog',
        surfaces: allSurfaces,
      },
      {
        title: 'Service Library',
        href: '/services',
        icon: Star,
        description: 'Browse service catalog',
        permissionModule: 'service_catalog',
        surfaces: allSurfaces,
      },
      {
        title: 'Repair Plans',
        href: '/repair-plans',
        icon: Archive,
        description: 'Manage repair plans',
        permissionModule: 'service_packages',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Store',
    items: [
      {
        title: 'Shopping',
        href: '/shopping',
        icon: Store,
        description: 'Browse products and tools',
        permissionModule: 'shopping',
        surfaces: allSurfaces,
      },
      {
        title: 'Shopping Cart',
        href: '/shopping/cart',
        icon: ShoppingCart,
        description: 'View cart and checkout',
        permissionModule: 'shopping',
        surfaces: allSurfaces,
      },
      {
        title: 'Wishlist',
        href: '/wishlist',
        icon: Heart,
        description: 'Your saved items',
        permissionModule: 'shopping',
        surfaces: allSurfaces,
      },
      {
        title: 'Orders',
        href: '/orders',
        icon: ShoppingBag,
        description: 'Order history and tracking',
        permissionModule: 'orders',
        surfaces: allSurfaces,
      },
    ],
  },
  {
    title: 'Tools',
    items: [
      {
        title: 'Technician Portal',
        href: '/technician-portal',
        icon: HardHat,
        description: 'Mobile-first technician interface',
        permissionModule: 'work_orders',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'AI Hub',
        href: '/ai-hub',
        icon: Brain,
        description: 'AI-powered automation and insights',
        permissionModule: 'analytics',
        surfaces: allSurfaces,
      },
      {
        title: 'Analytics',
        href: '/analytics',
        icon: BarChart3,
        description: 'Business analytics and insights',
        permissionModule: 'analytics',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Reports',
        href: '/reports',
        icon: FileBarChart2,
        description: 'Generate and view reports',
        permissionModule: 'reports',
        surfaces: navbarSurfaces,
      },
      {
        title: 'Forms',
        href: '/forms',
        icon: FormInput,
        description: 'Create and manage forms',
        permissionModule: 'reports',
        surfaces: allSurfaces,
      },
      {
        title: 'Feedback',
        href: '/feedback',
        icon: Star,
        description: 'Customer feedback and reviews',
        permissionModule: 'customers',
        surfaces: allSurfaces,
      },
      {
        title: 'Developer',
        href: '/developer',
        icon: Code,
        description: 'Developer tools and API',
        permissionModule: 'developer_tools',
        surfaces: ['sidebar', 'mobileHeader'],
      },
    ],
  },
  {
    title: 'Settings',
    items: [
      {
        title: 'Profile',
        href: '/profile',
        icon: User,
        description: 'Your profile settings',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Notifications',
        href: '/notifications',
        icon: Bell,
        description: 'Manage notifications',
        surfaces: sidebarAndMobileMenu,
      },
      {
        title: 'Settings',
        href: '/settings',
        icon: Settings,
        description: 'System configuration',
        permissionModule: 'settings',
        surfaces: sidebarAndMobileMenu,
      },
    ],
  },
  {
    title: 'Support',
    items: [
      {
        title: 'Help',
        href: '/help',
        icon: HelpCircle,
        description: 'Help and documentation',
        surfaces: allSurfaces,
      },
      {
        title: 'Audit Trail',
        href: '/audit-trail',
        icon: ClipboardList,
        description: 'System activity log',
        permissionModule: 'security',
        surfaces: allSurfaces,
      },
      {
        title: 'Security',
        href: '/security',
        icon: Shield,
        description: 'Security settings',
        permissionModule: 'security',
        surfaces: ['sidebar', 'mobileHeader'],
      },
    ],
  },
];

export function getNavigationForSurface(surface: NavigationSurface) {
  return appNavigation
    .map((section) => ({
      ...section,
      items: section.items.filter((item) => !item.surfaces || item.surfaces.includes(surface)),
    }))
    .filter((section) => section.items.length > 0);
}
