import { 
  Car, 
  Droplets, 
  Target, 
  Anchor, 
  Fuel, 
  LucideIcon,
  ShoppingCart,
  User,
  Briefcase,
  Crosshair,
  Package,
  BarChart3,
  FileText,
  CreditCard,
  Calendar,
  Shield,
  ArrowRightLeft,
  ShoppingBag,
  Wrench,
  Truck,
  Users,
  Gauge,
  Receipt,
  Ship,
  MapPin,
  Droplet,
  Link,
  Beaker,
  DollarSign,
  Route,
  CloudSun,
  Camera,
  Star,
  UserPlus,
  Calculator,
  Repeat,
  ClipboardList,
  Bell,
  Globe,
  Activity,
  History,
  FileSearch,
  Compass,
  Snowflake,
  CircleDollarSign,
  Smartphone,
  Container,
  PackageCheck,
  UserCheck,
  FolderOpen,
  Tractor,
  Building,
  Scissors,
  Home,
  Leaf,
  Zap,
  Paintbrush,
  // Additional icons for upcoming modules
  Waves,
  Flame,
  ThermometerSun,
  Bug,
  TreeDeciduous,
  Hammer,
  Fence,
  Sparkles,
  Shirt,
  Dog,
  Heart,
  Baby,
  GraduationCap,
  Music,
  Dumbbell,
  UtensilsCrossed,
  Coffee,
  Beer,
  Wine,
  Cake,
  Pizza,
  IceCream,
  Flower2,
  Mountain,
  Tent,
  Bike,
  Plane,
  Bus,
  Train,
  Warehouse,
  Factory,
  HardHat,
  Drill,
  Axe,
  Shovel,
  Flashlight,
  Lock,
  Key,
  Video,
  Tv,
  Wifi,
  Server,
  Database,
  Code,
  Printer,
  ScanLine,
  Cog,
  Settings,
  Cpu,
  Monitor,
  Speaker,
  Headphones,
  Gamepad2,
  Watch,
  Glasses,
  Gem,
  Crown,
  Ribbon,
  Gift,
  PartyPopper,
  Palette,
  Frame,
  ImageIcon,
  Brush,
  PenTool,
  Type,
  BookOpen,
  Newspaper,
  FileSpreadsheet,
  FilePlus,
  FolderHeart,
  Archive,
  Box,
  Boxes,
  Armchair,
  Lamp,
  BedDouble,
  Bath,
  ShowerHead,
  Plug,
  Fan,
  AirVent,
  Wind,
  Sun,
  Moon,
  Umbrella,
  CloudRain,
  Footprints,
  Bone,
  Cat,
  Bird,
  Fish,
  Turtle,
  Stethoscope,
  Pill,
  Syringe,
  Microscope,
  TestTube,
  Atom,
  Rocket,
  Satellite,
  Radio,
  Antenna,
  Phone,
  PhoneCall,
  MessageSquare,
  Mail,
  Send,
  Inbox,
  Share2,
  Network,
  Workflow,
  GitBranch,
  Terminal,
  Binary,
  QrCode,
  Fingerprint,
  Eye,
  EyeOff,
  Search,
  Filter,
  SortAsc,
  List,
  Grid3X3,
  LayoutDashboard,
  Columns,
  Rows,
  Table,
  PieChart,
  TrendingUp,
  LineChart,
  Award,
  Trophy,
  Medal,
  BadgeCheck,
  BadgeAlert,
  AlertTriangle,
  Info,
  HelpCircle,
  XCircle,
  CheckCircle,
  PlusCircle,
  MinusCircle,
  RefreshCw,
  RotateCcw,
  Undo,
  Redo,
  Copy,
  Clipboard,
  Trash2,
  Edit,
  PenLine,
  Highlighter,
  Eraser,
  Wand2,
  Sparkle,
  Lightbulb,
  Megaphone,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Pentagon,
  Hexagon,
  Octagon,
  Heart as HeartIcon,
  Bookmark,
  Flag,
  Pin,
  Navigation,
  Move,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  Fullscreen,
  SplitSquareVertical,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Subscript,
  Superscript,
  Heading1,
  Heading2,
  Heading3,
  ListOrdered,
  ListChecks,
  Quote,
  Code2,
  Braces,
  Terminal as TerminalIcon
} from 'lucide-react';

export interface ModuleSectionItem {
  title: string;
  href: string;
  icon: LucideIcon;
  description?: string;
  group?: string;
}

export interface ModuleRouteConfig {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  dashboardRoute: string;
  color: string;
  gradientFrom: string;
  gradientTo: string;
  sections?: ModuleSectionItem[];
}

export interface UpcomingModuleConfig {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  gradientFrom: string;
  gradientTo: string;
  expectedDate?: string;
  category?: string;
}

export const UPCOMING_MODULES: UpcomingModuleConfig[] = [
  // Home & Property Services
  {
    slug: 'hvac',
    name: 'HVAC Services',
    description: 'Heating, cooling, and ventilation with EPA 608 compliance',
    icon: ThermometerSun,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'pool-spa',
    name: 'Pool & Spa Services',
    description: 'Chemical tracking, water testing, and route management',
    icon: Waves,
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'plumbing',
    name: 'Plumbing Services',
    description: 'Residential and commercial plumbing with parts inventory',
    icon: Wrench,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'electrical',
    name: 'Electrical Services',
    description: 'Electrical contracting with permit and inspection tracking',
    icon: Zap,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'roofing',
    name: 'Roofing',
    description: 'Roof inspections, repairs, and project management',
    icon: Home,
    gradientFrom: 'from-slate-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'painting',
    name: 'Painting Services',
    description: 'Interior/exterior painting with estimating and crew dispatch',
    icon: Paintbrush,
    gradientFrom: 'from-violet-500',
    gradientTo: 'to-purple-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'handyman',
    name: 'Handyman Services',
    description: 'Multi-trade repairs with flexible pricing and scheduling',
    icon: Hammer,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'fencing',
    name: 'Fencing',
    description: 'Fence installation, repair, and material estimating',
    icon: Fence,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'landscaping',
    name: 'Landscaping',
    description: 'Lawn care, design, irrigation, and crew scheduling',
    icon: Leaf,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'pest-control',
    name: 'Pest Control',
    description: 'Route optimization, chemical compliance, and treatment plans',
    icon: Bug,
    gradientFrom: 'from-lime-500',
    gradientTo: 'to-green-600',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'septic',
    name: 'Septic Services',
    description: 'Pumping schedules, inspections, and compliance tracking',
    icon: Container,
    gradientFrom: 'from-stone-500',
    gradientTo: 'to-stone-700',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'window-cleaning',
    name: 'Window Cleaning',
    description: 'Commercial and residential window and gutter cleaning',
    icon: Sparkles,
    gradientFrom: 'from-sky-400',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'carpet-cleaning',
    name: 'Carpet Cleaning',
    description: 'Deep cleaning, stain removal, and upholstery services',
    icon: Sparkles,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-rose-500',
    expectedDate: 'Q2 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'chimney-sweep',
    name: 'Chimney Sweep',
    description: 'Chimney cleaning, inspections, and fireplace services',
    icon: Flame,
    gradientFrom: 'from-orange-600',
    gradientTo: 'to-red-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'garage-door',
    name: 'Garage Door Services',
    description: 'Installation, repair, and opener maintenance',
    icon: Home,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-gray-700',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'solar',
    name: 'Solar Installation',
    description: 'Panel installation, maintenance, and energy monitoring',
    icon: Sun,
    gradientFrom: 'from-yellow-400',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'insulation',
    name: 'Insulation Services',
    description: 'Spray foam, blown-in, and energy efficiency audits',
    icon: Home,
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-rose-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'flooring',
    name: 'Flooring',
    description: 'Hardwood, tile, carpet, and laminate installation',
    icon: Grid3X3,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-yellow-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'countertops',
    name: 'Countertop Installation',
    description: 'Granite, quartz, and solid surface fabrication',
    icon: Rows,
    gradientFrom: 'from-stone-400',
    gradientTo: 'to-stone-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'drywall',
    name: 'Drywall Services',
    description: 'Installation, finishing, and repair work',
    icon: Columns,
    gradientFrom: 'from-neutral-400',
    gradientTo: 'to-neutral-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'concrete',
    name: 'Concrete Services',
    description: 'Driveways, patios, foundations, and decorative concrete',
    icon: Box,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-slate-600',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },
  {
    slug: 'masonry',
    name: 'Masonry',
    description: 'Brick, stone, and block work with restoration',
    icon: Boxes,
    gradientFrom: 'from-red-700',
    gradientTo: 'to-red-900',
    expectedDate: 'Q3 2026',
    category: 'Home & Property Services',
  },

  // Construction & Trade
  {
    slug: 'general-contractor',
    name: 'General Contractor',
    description: 'Full construction project management and subcontractor coordination',
    icon: HardHat,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q2 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'demolition',
    name: 'Demolition',
    description: 'Structural demolition and debris removal',
    icon: Hammer,
    gradientFrom: 'from-red-600',
    gradientTo: 'to-red-800',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'excavation',
    name: 'Excavation',
    description: 'Site prep, grading, and earthwork services',
    icon: Shovel,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'framing',
    name: 'Framing',
    description: 'Residential and commercial framing projects',
    icon: Building,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'siding',
    name: 'Siding Installation',
    description: 'Vinyl, wood, fiber cement, and metal siding',
    icon: Columns,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-blue-700',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'deck-building',
    name: 'Deck Building',
    description: 'Custom decks, pergolas, and outdoor structures',
    icon: TreeDeciduous,
    gradientFrom: 'from-amber-700',
    gradientTo: 'to-yellow-800',
    expectedDate: 'Q3 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'cabinet-making',
    name: 'Cabinet Making',
    description: 'Custom cabinetry and millwork',
    icon: Box,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q4 2026',
    category: 'Construction & Trade',
  },
  {
    slug: 'welding',
    name: 'Welding Services',
    description: 'Metal fabrication and welding projects',
    icon: Flame,
    gradientFrom: 'from-orange-600',
    gradientTo: 'to-red-700',
    expectedDate: 'Q4 2026',
    category: 'Construction & Trade',
  },

  // Automotive & Transportation
  {
    slug: 'auto-detailing',
    name: 'Auto Detailing',
    description: 'Interior/exterior detailing and paint correction',
    icon: Sparkles,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-600',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'tire-shop',
    name: 'Tire Shop',
    description: 'Tire sales, mounting, balancing, and alignment',
    icon: Circle,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-gray-800',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'body-shop',
    name: 'Body Shop',
    description: 'Collision repair, paint, and insurance claims',
    icon: Car,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-pink-600',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'towing',
    name: 'Towing Services',
    description: 'Roadside assistance and vehicle recovery',
    icon: Truck,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q2 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'motorcycle',
    name: 'Motorcycle Services',
    description: 'Motorcycle repair and customization',
    icon: Bike,
    gradientFrom: 'from-red-600',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'rv-services',
    name: 'RV Services',
    description: 'RV repair, maintenance, and winterization',
    icon: Bus,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-teal-600',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'auto-glass',
    name: 'Auto Glass',
    description: 'Windshield repair and replacement',
    icon: Car,
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-blue-600',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'transmission',
    name: 'Transmission Shop',
    description: 'Transmission repair and rebuilds',
    icon: Cog,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-slate-700',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },
  {
    slug: 'muffler-exhaust',
    name: 'Muffler & Exhaust',
    description: 'Exhaust systems and emissions repair',
    icon: Wind,
    gradientFrom: 'from-zinc-500',
    gradientTo: 'to-zinc-700',
    expectedDate: 'Q3 2026',
    category: 'Automotive & Transportation',
  },

  // Personal Services
  {
    slug: 'salon',
    name: 'Salon & Spa',
    description: 'Beauty salon and spa appointment management',
    icon: Scissors,
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-rose-600',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'barbershop',
    name: 'Barbershop',
    description: 'Barber appointments and client management',
    icon: Scissors,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-slate-700',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'nail-salon',
    name: 'Nail Salon',
    description: 'Manicure, pedicure, and nail art services',
    icon: Sparkles,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-fuchsia-500',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'esthetician',
    name: 'Esthetician',
    description: 'Lashes, brows, facials, waxing, and skincare services',
    icon: Sparkles,
    gradientFrom: 'from-rose-400',
    gradientTo: 'to-pink-500',
    expectedDate: 'Q2 2026',
    category: 'Personal Services',
  },
  {
    slug: 'tattoo',
    name: 'Tattoo Studio',
    description: 'Tattoo appointments and portfolio management',
    icon: PenTool,
    gradientFrom: 'from-gray-700',
    gradientTo: 'to-black',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'massage',
    name: 'Massage Therapy',
    description: 'Massage bookings and treatment tracking',
    icon: Heart,
    gradientFrom: 'from-purple-400',
    gradientTo: 'to-violet-500',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'personal-training',
    name: 'Personal Training',
    description: 'Fitness coaching and client progress tracking',
    icon: Dumbbell,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-600',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'yoga-pilates',
    name: 'Yoga & Pilates Studio',
    description: 'Class scheduling and membership management',
    icon: Heart,
    gradientFrom: 'from-teal-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'photography',
    name: 'Photography',
    description: 'Photo shoots, editing, and client galleries',
    icon: Camera,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'videography',
    name: 'Videography',
    description: 'Video production and event filming',
    icon: Video,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-rose-600',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'tutoring',
    name: 'Tutoring',
    description: 'Educational tutoring and lesson scheduling',
    icon: GraduationCap,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q3 2026',
    category: 'Personal Services',
  },
  {
    slug: 'music-lessons',
    name: 'Music Lessons',
    description: 'Music instruction and recital management',
    icon: Music,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-pink-600',
    expectedDate: 'Q4 2026',
    category: 'Personal Services',
  },

  // Pet Services
  {
    slug: 'pet-grooming',
    name: 'Pet Grooming',
    description: 'Grooming appointments and pet profiles',
    icon: Dog,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q2 2026',
    category: 'Pet Services',
  },
  {
    slug: 'veterinary',
    name: 'Veterinary Clinic',
    description: 'Pet health records and appointment scheduling',
    icon: Stethoscope,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-600',
    expectedDate: 'Q2 2026',
    category: 'Pet Services',
  },
  {
    slug: 'pet-boarding',
    name: 'Pet Boarding',
    description: 'Boarding reservations and pet care tracking',
    icon: Home,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-600',
    expectedDate: 'Q3 2026',
    category: 'Pet Services',
  },
  {
    slug: 'dog-walking',
    name: 'Dog Walking',
    description: 'Walk scheduling and route tracking',
    icon: Footprints,
    gradientFrom: 'from-green-400',
    gradientTo: 'to-lime-500',
    expectedDate: 'Q3 2026',
    category: 'Pet Services',
  },
  {
    slug: 'pet-sitting',
    name: 'Pet Sitting',
    description: 'In-home pet care and daily updates',
    icon: Cat,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-600',
    expectedDate: 'Q3 2026',
    category: 'Pet Services',
  },
  {
    slug: 'dog-training',
    name: 'Dog Training',
    description: 'Training sessions and progress tracking',
    icon: Dog,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-600',
    expectedDate: 'Q4 2026',
    category: 'Pet Services',
  },

  // Food & Beverage
  {
    slug: 'catering',
    name: 'Catering',
    description: 'Event catering and menu planning',
    icon: UtensilsCrossed,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-500',
    expectedDate: 'Q3 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'food-truck',
    name: 'Food Truck',
    description: 'Mobile food service and location scheduling',
    icon: Truck,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-orange-500',
    expectedDate: 'Q3 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'bakery',
    name: 'Bakery',
    description: 'Custom orders and production scheduling',
    icon: Cake,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-rose-500',
    expectedDate: 'Q3 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'coffee-shop',
    name: 'Coffee Shop',
    description: 'Cafe operations and inventory management',
    icon: Coffee,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q4 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'brewery',
    name: 'Brewery',
    description: 'Brew tracking, taproom, and distribution',
    icon: Beer,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-yellow-600',
    expectedDate: 'Q4 2026',
    category: 'Food & Beverage',
  },
  {
    slug: 'winery',
    name: 'Winery',
    description: 'Wine production and tasting room management',
    icon: Wine,
    gradientFrom: 'from-red-700',
    gradientTo: 'to-purple-800',
    expectedDate: 'Q4 2026',
    category: 'Food & Beverage',
  },

  // Technology & Electronics
  {
    slug: 'computer-repair',
    name: 'Computer Repair',
    description: 'PC and laptop diagnostics and repair',
    icon: Monitor,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q2 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'phone-repair',
    name: 'Phone Repair',
    description: 'Smartphone and tablet repair services',
    icon: Smartphone,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q2 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'it-services',
    name: 'IT Services',
    description: 'Managed IT and network support',
    icon: Server,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-600',
    expectedDate: 'Q2 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'security-systems',
    name: 'Security Systems',
    description: 'Alarm, camera, and access control installation',
    icon: Lock,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-emerald-700',
    expectedDate: 'Q3 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'home-theater',
    name: 'Home Theater',
    description: 'Audio/video installation and smart home',
    icon: Tv,
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q3 2026',
    category: 'Technology & Electronics',
  },
  {
    slug: 'appliance-repair',
    name: 'Appliance Repair',
    description: 'Major appliance diagnostics and repair',
    icon: Cog,
    gradientFrom: 'from-zinc-500',
    gradientTo: 'to-zinc-700',
    expectedDate: 'Q3 2026',
    category: 'Technology & Electronics',
  },

  // Specialty & Niche
  {
    slug: 'locksmith',
    name: 'Locksmith',
    description: 'Lock installation, repair, and emergency services',
    icon: Key,
    gradientFrom: 'from-yellow-600',
    gradientTo: 'to-amber-700',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'moving',
    name: 'Moving Services',
    description: 'Residential and commercial moving',
    icon: Truck,
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-amber-600',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'storage',
    name: 'Storage Facilities',
    description: 'Unit rentals and access management',
    icon: Warehouse,
    gradientFrom: 'from-gray-500',
    gradientTo: 'to-slate-600',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'junk-removal',
    name: 'Junk Removal',
    description: 'Hauling and disposal services',
    icon: Trash2,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-emerald-700',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'tree-service',
    name: 'Tree Service',
    description: 'Tree trimming, removal, and stump grinding',
    icon: TreeDeciduous,
    gradientFrom: 'from-green-700',
    gradientTo: 'to-green-900',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'irrigation',
    name: 'Irrigation',
    description: 'Sprinkler installation and repair',
    icon: Droplet,
    gradientFrom: 'from-blue-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'snow-removal',
    name: 'Snow Removal',
    description: 'Plowing, salting, and snow management',
    icon: Snowflake,
    gradientFrom: 'from-blue-300',
    gradientTo: 'to-cyan-400',
    expectedDate: 'Q4 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'event-planning',
    name: 'Event Planning',
    description: 'Event coordination and vendor management',
    icon: PartyPopper,
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-purple-600',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'dj-entertainment',
    name: 'DJ & Entertainment',
    description: 'Event booking and equipment tracking',
    icon: Music,
    gradientFrom: 'from-violet-500',
    gradientTo: 'to-purple-700',
    expectedDate: 'Q4 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'cleaning-residential',
    name: 'Residential Cleaning',
    description: 'House cleaning and maid services',
    icon: Sparkles,
    gradientFrom: 'from-cyan-400',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'cleaning-commercial',
    name: 'Commercial Cleaning',
    description: 'Janitorial and office cleaning',
    icon: Building,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q2 2026',
    category: 'Specialty & Niche',
  },
  {
    slug: 'laundry',
    name: 'Laundry Services',
    description: 'Dry cleaning and laundry pickup/delivery',
    icon: Shirt,
    gradientFrom: 'from-blue-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q3 2026',
    category: 'Specialty & Niche',
  },

  // Agriculture & Outdoor
  {
    slug: 'agriculture',
    name: 'Agriculture & Farm',
    description: 'Farm equipment service and agricultural operations',
    icon: Tractor,
    gradientFrom: 'from-yellow-500',
    gradientTo: 'to-amber-600',
    expectedDate: 'Q3 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'lawn-mower',
    name: 'Lawn Mower Repair',
    description: 'Small engine and mower maintenance',
    icon: Cog,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-lime-600',
    expectedDate: 'Q3 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'outdoor-power',
    name: 'Outdoor Power Equipment',
    description: 'Chainsaw, trimmer, and blower service',
    icon: Axe,
    gradientFrom: 'from-orange-600',
    gradientTo: 'to-red-600',
    expectedDate: 'Q3 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'nursery',
    name: 'Plant Nursery',
    description: 'Plant inventory and sales management',
    icon: Flower2,
    gradientFrom: 'from-green-400',
    gradientTo: 'to-emerald-500',
    expectedDate: 'Q4 2026',
    category: 'Agriculture & Outdoor',
  },
  {
    slug: 'greenhouse',
    name: 'Greenhouse',
    description: 'Growing operations and climate control',
    icon: Leaf,
    gradientFrom: 'from-lime-500',
    gradientTo: 'to-green-600',
    expectedDate: 'Q4 2026',
    category: 'Agriculture & Outdoor',
  },

  // Professional Services
  {
    slug: 'consulting',
    name: 'Consulting',
    description: 'Client engagements and project tracking',
    icon: Briefcase,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'accounting',
    name: 'Accounting Firm',
    description: 'Client management and tax preparation',
    icon: Calculator,
    gradientFrom: 'from-green-600',
    gradientTo: 'to-emerald-700',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'legal',
    name: 'Legal Services',
    description: 'Case management and billing',
    icon: FileText,
    gradientFrom: 'from-gray-700',
    gradientTo: 'to-slate-900',
    expectedDate: 'Q4 2026',
    category: 'Professional Services',
  },
  {
    slug: 'real-estate',
    name: 'Real Estate',
    description: 'Property listings and transaction management',
    icon: Home,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-600',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'property-management',
    name: 'Property Management',
    description: 'Rental properties and tenant management',
    icon: Building,
    gradientFrom: 'from-slate-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q3 2026',
    category: 'Professional Services',
  },
  {
    slug: 'insurance',
    name: 'Insurance Agency',
    description: 'Policy management and claims tracking',
    icon: Shield,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-indigo-700',
    expectedDate: 'Q4 2026',
    category: 'Professional Services',
  },

  // Healthcare & Wellness
  {
    slug: 'chiropractic',
    name: 'Chiropractic',
    description: 'Patient scheduling and treatment plans',
    icon: Activity,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-teal-600',
    expectedDate: 'Q3 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'dental',
    name: 'Dental Practice',
    description: 'Patient records and appointment management',
    icon: Sparkles,
    gradientFrom: 'from-cyan-400',
    gradientTo: 'to-blue-500',
    expectedDate: 'Q3 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'physical-therapy',
    name: 'Physical Therapy',
    description: 'Therapy sessions and progress tracking',
    icon: Activity,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q3 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'optometry',
    name: 'Optometry',
    description: 'Eye exams and optical dispensing',
    icon: Eye,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-600',
    expectedDate: 'Q4 2026',
    category: 'Healthcare & Wellness',
  },
  {
    slug: 'medical-spa',
    name: 'Medical Spa',
    description: 'Aesthetic treatments and consultations',
    icon: Sparkles,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-rose-500',
    expectedDate: 'Q4 2026',
    category: 'Healthcare & Wellness',
  },

  // Childcare & Education
  {
    slug: 'daycare',
    name: 'Daycare Center',
    description: 'Child enrollment and daily tracking',
    icon: Baby,
    gradientFrom: 'from-pink-400',
    gradientTo: 'to-purple-500',
    expectedDate: 'Q3 2026',
    category: 'Childcare & Education',
  },
  {
    slug: 'after-school',
    name: 'After School Program',
    description: 'Program registration and attendance',
    icon: GraduationCap,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q4 2026',
    category: 'Childcare & Education',
  },
  {
    slug: 'summer-camp',
    name: 'Summer Camp',
    description: 'Camp registration and activity planning',
    icon: Tent,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-600',
    expectedDate: 'Q4 2026',
    category: 'Childcare & Education',
  },

  // Recreation & Sports
  {
    slug: 'golf-course',
    name: 'Golf Course',
    description: 'Tee times and membership management',
    icon: Flag,
    gradientFrom: 'from-green-500',
    gradientTo: 'to-lime-600',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'ski-snowboard',
    name: 'Ski & Snowboard',
    description: 'Equipment rentals and lessons',
    icon: Mountain,
    gradientFrom: 'from-blue-400',
    gradientTo: 'to-cyan-500',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'bike-shop',
    name: 'Bike Shop',
    description: 'Bicycle sales, repair, and rentals',
    icon: Bike,
    gradientFrom: 'from-red-500',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q3 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'fishing-charter',
    name: 'Fishing Charter',
    description: 'Charter bookings and trip management',
    icon: Fish,
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-cyan-700',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },
  {
    slug: 'hunting-guide',
    name: 'Hunting Guide',
    description: 'Hunt bookings and licensing compliance',
    icon: Target,
    gradientFrom: 'from-green-700',
    gradientTo: 'to-green-900',
    expectedDate: 'Q4 2026',
    category: 'Recreation & Sports',
  },

  // Retail & Crafts
  {
    slug: 'jewelry',
    name: 'Jewelry Store',
    description: 'Custom orders and repair services',
    icon: Gem,
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-pink-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'watch-repair',
    name: 'Watch Repair',
    description: 'Watch servicing and parts tracking',
    icon: Watch,
    gradientFrom: 'from-gray-600',
    gradientTo: 'to-slate-800',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'upholstery',
    name: 'Upholstery',
    description: 'Furniture reupholstering and fabric selection',
    icon: Armchair,
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-yellow-700',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'tailor',
    name: 'Tailor & Alterations',
    description: 'Clothing alterations and custom tailoring',
    icon: Scissors,
    gradientFrom: 'from-indigo-500',
    gradientTo: 'to-purple-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'picture-framing',
    name: 'Picture Framing',
    description: 'Custom framing and matting',
    icon: Frame,
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-orange-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
  {
    slug: 'printing',
    name: 'Print Shop',
    description: 'Commercial printing and signage',
    icon: Printer,
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-indigo-600',
    expectedDate: 'Q4 2026',
    category: 'Retail & Crafts',
  },
];

export const MODULE_ROUTES: Record<string, ModuleRouteConfig> = {
  automotive: {
    slug: 'automotive',
    name: 'Automotive Repair',
    description: 'Full-service auto repair shop management',
    icon: Car,
    dashboardRoute: '/automotive',
    color: 'hsl(var(--primary))',
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-blue-600',
    sections: [
      // Dashboard
      { title: 'Dashboard', href: '/automotive', icon: Gauge, description: 'Module overview and KPIs', group: 'Dashboard' },
      
      // Services
      { title: 'All Jobs', href: '/work-orders', icon: Briefcase, description: 'Work orders and repairs', group: 'Services' },
      { title: 'Quotes', href: '/quotes', icon: FileText, description: 'Estimates and quotes', group: 'Services' },
      { title: 'Invoices', href: '/invoices', icon: Receipt, description: 'Billing and invoices', group: 'Services' },
      { title: 'Payments', href: '/payments', icon: CreditCard, description: 'Payment processing', group: 'Services' },
      { title: 'Service Packages', href: '/service-packages', icon: Package, description: 'Service bundles', group: 'Services' },
      
      // Customers
      { title: 'Customers', href: '/customers', icon: Users, description: 'Customer management', group: 'Customers' },
      { title: 'Vehicle History', href: '/automotive/vehicle-history', icon: History, description: 'Complete service history', group: 'Customers' },
      
      // Inventory
      { title: 'Parts', href: '/inventory', icon: Package, description: 'Parts inventory', group: 'Inventory' },
      { title: 'Parts Tracking', href: '/parts-tracking', icon: Package, description: 'Track parts orders', group: 'Inventory' },
      { title: 'Suppliers', href: '/inventory-suppliers', icon: Users, description: 'Vendor management', group: 'Inventory' },
      
      // Scheduling
      { title: 'Appointments', href: '/booking-management', icon: Calendar, description: 'Booking management', group: 'Scheduling' },
      { title: 'Planner', href: '/planner', icon: Calendar, description: 'Job planner', group: 'Scheduling' },
      { title: 'Calendar', href: '/calendar', icon: Calendar, description: 'Service calendar', group: 'Scheduling' },
      
      // Communications
      { title: 'Customer Comms', href: '/customer-comms', icon: Bell, description: 'Customer messaging', group: 'Communications' },
      { title: 'Call Logger', href: '/call-logger', icon: Bell, description: 'Call tracking', group: 'Communications' },
      
      // Marketing
      { title: 'Email Campaigns', href: '/email-campaigns', icon: Globe, description: 'Email marketing', group: 'Marketing' },
      { title: 'SMS Management', href: '/sms-management', icon: Smartphone, description: 'Text messaging', group: 'Marketing' },
      
      // Operations
      { title: 'Daily Logs', href: '/daily-logs', icon: ClipboardList, description: 'Daily operations', group: 'Operations' },
      { title: 'Service Board', href: '/service-board', icon: Briefcase, description: 'Live job board', group: 'Operations' },
      
      // Equipment & Tools
      { title: 'Equipment', href: '/equipment', icon: Wrench, description: 'Shop equipment', group: 'Equipment & Tools' },
      { title: 'Maintenance', href: '/maintenance-requests', icon: Wrench, description: 'Equipment maintenance', group: 'Equipment & Tools' },
      
      // Fleet
      { title: 'Vehicles', href: '/vehicles', icon: Car, description: 'Customer vehicles', group: 'Fleet' },
      { title: 'Fleet Management', href: '/fleet-management', icon: Truck, description: 'Fleet tracking', group: 'Fleet' },
      { title: 'Fuel Management', href: '/fuel-management', icon: Fuel, description: 'Fuel tracking', group: 'Fleet' },
      { title: 'Tire Management', href: '/tire-management', icon: Car, description: 'Tire tracking', group: 'Fleet' },
      
      // Safety & Compliance
      { title: 'Safety Dashboard', href: '/safety', icon: Shield, description: 'Safety overview', group: 'Safety & Compliance' },
      { title: 'DVIR', href: '/safety/dvir', icon: ClipboardList, description: 'Vehicle inspections', group: 'Safety & Compliance' },
      { title: 'Inspections', href: '/safety/inspections', icon: Shield, description: 'Safety inspections', group: 'Safety & Compliance' },
      
      // Company
      { title: 'Company Profile', href: '/company-profile', icon: Users, description: 'Business info', group: 'Company' },
      { title: 'Team', href: '/team', icon: Users, description: 'Staff management', group: 'Company' },
      { title: 'Settings', href: '/settings', icon: Wrench, description: 'Module settings', group: 'Company' },
      
      // Automotive-Specific
      { title: 'Diagnostics', href: '/automotive/diagnostics', icon: Activity, description: 'Diagnostic tools', group: 'Automotive' },
      { title: 'Labor Rates', href: '/automotive/labor-rates', icon: DollarSign, description: 'Rate management', group: 'Automotive' },
      { title: 'TSB & Recalls', href: '/automotive/recalls', icon: FileSearch, description: 'Technical bulletins', group: 'Automotive' },
    ],
  },
  power_washing: {
    slug: 'power_washing',
    name: 'Power Washing',
    description: 'Pressure washing business management',
    icon: Droplets,
    dashboardRoute: '/power-washing',
    color: 'hsl(var(--chart-2))',
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-cyan-600',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/power-washing', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'All Jobs', href: '/power-washing/jobs', icon: Briefcase, description: 'Job management' },
      { title: 'Customers', href: '/power-washing/customers', icon: Users, description: 'Customer management' },
      { title: 'Quotes', href: '/power-washing/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/power-washing/invoices', icon: Receipt, description: 'Billing and invoices' },
      { title: 'Payments', href: '/power-washing/payments', icon: CreditCard, description: 'Payment processing' },
      { title: 'Schedule', href: '/power-washing/schedule', icon: Calendar, description: 'Job scheduling' },
      // Power Washing-Specific Features
      { title: 'Chemicals', href: '/power-washing/chemicals', icon: Beaker, description: 'Chemical inventory and SDS' },
      { title: 'Formulas', href: '/power-washing/formulas', icon: Calculator, description: 'Mix ratios and formulas' },
      { title: 'Price Book', href: '/power-washing/price-book', icon: DollarSign, description: 'Service pricing' },
      { title: 'Routes', href: '/power-washing/routes', icon: Route, description: 'Route optimization' },
      { title: 'Weather', href: '/power-washing/weather', icon: CloudSun, description: 'Weather forecasts' },
      { title: 'Equipment', href: '/power-washing/equipment', icon: Wrench, description: 'Equipment management' },
      { title: 'Fleet', href: '/power-washing/fleet', icon: Truck, description: 'Vehicle fleet' },
      { title: 'Photos', href: '/power-washing/photos', icon: Camera, description: 'Before/after photos' },
      { title: 'Reviews', href: '/power-washing/reviews', icon: Star, description: 'Customer reviews' },
      { title: 'Leads', href: '/power-washing/leads', icon: UserPlus, description: 'Lead management' },
      { title: 'Recurring', href: '/power-washing/recurring', icon: Repeat, description: 'Recurring schedules' },
      { title: 'Subscriptions', href: '/power-washing/subscriptions', icon: CreditCard, description: 'Subscription plans' },
      { title: 'Reports', href: '/power-washing/reports', icon: BarChart3, description: 'Analytics and reports' },
      { title: 'Field View', href: '/power-washing/field-view', icon: Smartphone, description: 'Mobile field app' },
      { title: 'Customer Portal', href: '/power-washing/portal', icon: Globe, description: 'Customer self-service' },
    ],
  },
  gunsmith: {
    slug: 'gunsmith',
    name: 'Gunsmith',
    description: 'Firearms service and compliance tracking',
    icon: Target,
    dashboardRoute: '/gunsmith',
    color: 'hsl(var(--chart-4))',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-amber-600',
    sections: [
      // Dashboard
      { title: 'Dashboard', href: '/gunsmith', icon: Gauge, group: 'Dashboard' },
      // Services
      { title: 'All Jobs', href: '/gunsmith/jobs', icon: Briefcase, group: 'Services' },
      { title: 'Quotes', href: '/gunsmith/quotes', icon: FileText, group: 'Services' },
      { title: 'Appointments', href: '/gunsmith/appointments', icon: Calendar, group: 'Services' },
      // Customers
      { title: 'Customers', href: '/gunsmith/customers', icon: Users, group: 'Customers' },
      { title: 'Firearms', href: '/gunsmith/firearms', icon: Crosshair, group: 'Customers' },
      // Inventory
      { title: 'Parts', href: '/gunsmith/parts', icon: Package, group: 'Inventory' },
      { title: 'Parts on Order', href: '/gunsmith/parts-on-order', icon: ShoppingBag, group: 'Inventory' },
      { title: 'Inventory', href: '/gunsmith/inventory', icon: BarChart3, group: 'Inventory' },
      // Billing
      { title: 'Invoices', href: '/gunsmith/invoices', icon: Receipt, group: 'Billing' },
      { title: 'Payments', href: '/gunsmith/payments', icon: CreditCard, group: 'Billing' },
      // Compliance
      { title: 'Compliance', href: '/gunsmith/compliance', icon: Shield, group: 'Compliance' },
      { title: 'Transfers', href: '/gunsmith/transfers', icon: ArrowRightLeft, group: 'Compliance' },
      { title: 'Consignments', href: '/gunsmith/consignments', icon: ShoppingBag, group: 'Compliance' },
      // Resources
      { title: 'Resources', href: '/gunsmith/resources', icon: Link, group: 'Resources' },
      { title: 'Feedback Log', href: '/gunsmith/change-log', icon: ClipboardList, group: 'Resources' },
      // Settings
      { title: 'Settings', href: '/gunsmith/settings', icon: Settings, group: 'Settings' },
      { title: 'Team', href: '/gunsmith/team', icon: Users, group: 'Settings' },
      { title: 'Roles', href: '/gunsmith/roles', icon: Shield, group: 'Settings' },
    ],
  },
  marine: {
    slug: 'marine',
    name: 'Marine Services',
    description: 'Boat and watercraft maintenance',
    icon: Anchor,
    dashboardRoute: '/marine-services',
    color: 'hsl(var(--chart-3))',
    gradientFrom: 'from-teal-500',
    gradientTo: 'to-teal-600',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/marine-services', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'All Jobs', href: '/marine-services/jobs', icon: Briefcase, description: 'Work orders' },
      { title: 'Vessels', href: '/marine-services/vessels', icon: Ship, description: 'Vessel registry' },
      { title: 'Parts', href: '/marine-services/parts', icon: Package, description: 'Parts inventory' },
      { title: 'Quotes', href: '/marine-services/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/marine-services/invoices', icon: Receipt, description: 'Billing and invoices' },
      { title: 'Payments', href: '/marine-services/payments', icon: CreditCard, description: 'Payment processing' },
      { title: 'Dock Schedule', href: '/marine-services/schedule', icon: Calendar, description: 'Dock scheduling' },
      // Marine-Specific Features
      { title: 'Sea Trials', href: '/marine-services/sea-trials', icon: Compass, description: 'Sea trial scheduling and logs' },
      { title: 'Haul-Outs', href: '/marine-services/haul-outs', icon: Anchor, description: 'Haul-out scheduling' },
      { title: 'Winterization', href: '/marine-services/winterization', icon: Snowflake, description: 'Winterization tracking' },
      { title: 'Compliance', href: '/marine-services/compliance', icon: Shield, description: 'Coast Guard compliance' },
    ],
  },
  fuel_delivery: {
    slug: 'fuel_delivery',
    name: 'Fuel Delivery',
    description: 'Fuel delivery and tank management',
    icon: Fuel,
    dashboardRoute: '/fuel-delivery',
    color: 'hsl(var(--chart-5))',
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-orange-600',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/fuel-delivery', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'Orders', href: '/fuel-delivery/orders', icon: ClipboardList, description: 'Delivery orders' },
      { title: 'Customers', href: '/fuel-delivery/customers', icon: Users, description: 'Customer management' },
      { title: 'Quotes', href: '/fuel-delivery/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/fuel-delivery/invoices', icon: Receipt, description: 'Billing and invoices' },
      // Tank Management
      { title: 'Tanks', href: '/fuel-delivery/tanks', icon: Container, description: 'Tank registry' },
      { title: 'Tidy Tanks', href: '/fuel-delivery/tidy-tanks', icon: PackageCheck, description: 'Tank maintenance' },
      { title: 'Tank Fills', href: '/fuel-delivery/tank-fills', icon: Droplet, description: 'Fill history' },
      { title: 'Locations', href: '/fuel-delivery/locations', icon: MapPin, description: 'Delivery locations' },
      // Fleet & Delivery
      { title: 'Routes', href: '/fuel-delivery/routes', icon: Route, description: 'Route optimization' },
      { title: 'Trucks', href: '/fuel-delivery/trucks', icon: Truck, description: 'Delivery trucks' },
      { title: 'Drivers', href: '/fuel-delivery/drivers', icon: UserCheck, description: 'Driver management' },
      { title: 'Equipment', href: '/fuel-delivery/equipment', icon: Wrench, description: 'Equipment tracking' },
      { title: 'Completions', href: '/fuel-delivery/completions', icon: FolderOpen, description: 'Completed deliveries' },
      // Products & Pricing
      { title: 'Products', href: '/fuel-delivery/products', icon: Fuel, description: 'Fuel products' },
      { title: 'Pricing', href: '/fuel-delivery/pricing', icon: CircleDollarSign, description: 'Price management' },
      { title: 'Inventory', href: '/fuel-delivery/inventory', icon: BarChart3, description: 'Fuel inventory' },
      // Mobile
      { title: 'Driver App', href: '/fuel-delivery/driver-app', icon: Smartphone, description: 'Mobile driver app' },
    ],
  },
  water_delivery: {
    slug: 'water_delivery',
    name: 'Water Delivery',
    description: 'Water delivery, tank management, and route optimization',
    icon: Droplet,
    dashboardRoute: '/water-delivery',
    color: 'hsl(var(--chart-1))',
    gradientFrom: 'from-cyan-500',
    gradientTo: 'to-blue-600',
    sections: [
      // Core Operations
      { title: 'Dashboard', href: '/water-delivery', icon: Gauge, description: 'Module overview and KPIs' },
      { title: 'Orders', href: '/water-delivery/orders', icon: ClipboardList, description: 'Delivery orders' },
      { title: 'Customers', href: '/water-delivery/customers', icon: Users, description: 'Customer management' },
      { title: 'Quotes', href: '/water-delivery/quotes', icon: FileText, description: 'Estimates and quotes' },
      { title: 'Invoices', href: '/water-delivery/invoices', icon: Receipt, description: 'Billing and invoices' },
      // Tank Management
      { title: 'Tanks', href: '/water-delivery/tanks', icon: Container, description: 'Tank registry' },
      { title: 'Tidy Tanks', href: '/water-delivery/tidy-tanks', icon: PackageCheck, description: 'Tank maintenance' },
      { title: 'Tank Fills', href: '/water-delivery/tank-fills', icon: Droplet, description: 'Fill history' },
      { title: 'Locations', href: '/water-delivery/locations', icon: MapPin, description: 'Delivery locations' },
      // Fleet & Delivery
      { title: 'Routes', href: '/water-delivery/routes', icon: Route, description: 'Route optimization' },
      { title: 'Trucks', href: '/water-delivery/trucks', icon: Truck, description: 'Water trucks' },
      { title: 'Drivers', href: '/water-delivery/drivers', icon: UserCheck, description: 'Driver management' },
      { title: 'Equipment', href: '/water-delivery/equipment', icon: Wrench, description: 'Equipment tracking' },
      { title: 'Equipment Filters', href: '/water-delivery/equipment-filters', icon: Filter, description: 'Filter maintenance' },
      { title: 'Deliveries', href: '/water-delivery/deliveries', icon: FolderOpen, description: 'Completed deliveries' },
      // Products & Pricing
      { title: 'Products', href: '/water-delivery/products', icon: Droplet, description: 'Water products' },
      { title: 'Pricing', href: '/water-delivery/pricing', icon: CircleDollarSign, description: 'Price management' },
      { title: 'Inventory', href: '/water-delivery/inventory', icon: BarChart3, description: 'Water inventory' },
      { title: 'Purchases', href: '/water-delivery/purchases', icon: ShoppingCart, description: 'Purchase orders' },
      // Mobile
      { title: 'Driver App', href: '/water-delivery/driver-app', icon: Smartphone, description: 'Mobile driver app' },
      // Settings
      { title: 'Profile', href: '/water-delivery/profile', icon: User, description: 'Module profile' },
      { title: 'Settings', href: '/water-delivery/settings', icon: Settings, description: 'Module settings' },
    ],
  },
};

export const getModuleRoute = (slug: string): ModuleRouteConfig | undefined => {
  return MODULE_ROUTES[slug];
};

export const getAllModuleRoutes = (): ModuleRouteConfig[] => {
  return Object.values(MODULE_ROUTES);
};

export const getModuleSections = (slug: string): ModuleSectionItem[] => {
  return MODULE_ROUTES[slug]?.sections || [];
};
